import React, { useEffect } from "react";
import Footer from "../../components/footer/Footer";
import Head from "next/head";
import Profile from "../../components/Profile";
import Navbar from "../../components/Navbar/NavbarDetail";
import styles from "../../styles/Home.module.css";
import axios from "axios";
import { useRouter } from "next/router";
import { useState } from "react";

/* SSR */
// export async function getServerSideProps(context) {
//   const id = context.params.id
//   console.log("ini id", id)
//   const res = await axios.get(`http://localhost:8080/worker/${id}`);
//   console.log("ini res", res)
//   return {
//     props: { data: res.data.data.worker[0] },
//   };
// }


const ProfileDetails = () => {
  const [portfolio, setPortfolio] = useState([]);
  const [experience, setExperience] = useState([]);
  const [data, setData] = useState([]);
  const Router = useRouter();
  const id = Router.query.id;

  const fetchProfil = async () => {
    const result = await axios.get(`${process.env.API_BACKEND}worker/${id}`)
    setData(result.data.data);
  };

  console.log(id);
  console.log(data);
  const fetchPort = async () => {
    const result = await axios.get(`${process.env.API_BACKEND}portfolio/${id}`)
    setPortfolio(result.data.data);
  };

  const fetchExperience = async () => {
    const result = await axios.get(`${process.env.API_BACKEND}experience/${id}`);
    setExperience(result.data.data)
  };

  useEffect(() => {
    fetchPort();
    fetchExperience();
    fetchProfil()
  }, [])

  return (
    <div className="body">

      <div className={`${styles.bg_profile}`}>
        <Head>
          <title>Hirejob</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/vercel.svg" />
        </Head>
        <Navbar />
        <div className={`${styles.bg}`}></div>
        <div></div>
        <Profile detail={data} portfolio={portfolio} experience={experience}></Profile>
      </div>
      <Footer />
    </div>
  );
}

export default ProfileDetails;