import React from "react";
import Footer from "../../../components/footer/Footer";
import Head from "next/head";
import Profile from "../../../components/Profile/recruiter";
import Navbar from "../../../components/Navbar/NavbarDetail";
import styles from "../../../styles/Home.module.css";
import axios from "axios";
/* SSR */
export async function getServerSideProps(context) {
  const id = context.params.id
  console.log(id)
  const res = await axios.get(`${process.env.API_BACKEND}recruiter/${id}`);
  console.log('data recruiter',res.data);
  return {
    props: { data: res.data.data[0] },
  };
}

const ProfileDetails = ({ data }) => {
  return (
    <div className="body">

      <div className={`${styles.bg_profile}`}>
        <Head>
          <title>Hirejob</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/vercel.svg" />
        </Head>
        <Navbar />
        <div></div>
        <Profile detail={data}></Profile>
      </div>
      <Footer />
    </div>
  );
}

export default ProfileDetails;