import Head from "next/head";
import React, { useEffect,  useState } from "react";
import Portofolio from "../../components/Portofolio/index";
import Pengalaman from "../../components/experiences/index";
import styles from "../../styles/Profile.module.css";
import Image from "next/image";
import PhotoProfile from "../../assets/iconpp.jpg";
import axios from "axios";
import Link from "next/link";
import Footer from "../../components/footer/Footer";
import Navbar from "../../components/Navbar/NavbarDetail";
import Cookies from "js-cookie";
import Swal from "sweetalert2";

const Profile = () => {
  const id = Cookies.get("id");
  const token = Cookies.get("token");
  const role = Cookies.get("role");
  const [image, setImage] = useState(null);
  const [detail, setDetail] = useState([]);
  const [loading, setLoading] = useState(false);
  const [portfolio, setPortfolio] = useState([]);
  const [experience, setExperience] = useState([]);
  console.log(portfolio);
  console.log(experience);
  console.log(detail);
  const fetch = async () => {
    if(role){
      const result = await axios.get(
        `${process.env.API_BACKEND}authRecruiter/profile`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );
      setDetail(result.data.data);
      setLoading(false);
    }else{
      const result = await axios.get(
        `${process.env.API_BACKEND}authWorker/profile`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );
      setDetail(result.data.data[0]);
      setLoading(false);
    }

    }

  const fetchPort = async () => {
    const result = await axios.get(`${process.env.API_BACKEND}portfolio/${id}`);

    setPortfolio(result.data.data);
  };

  const fetchExp = async () => {
    const result = await axios.get(
      `${process.env.API_BACKEND}experience/${id}`
    );

    setExperience(result.data.data);
  };

  const imageChangeHandler = (e) => {
    setImage(e.target.files[0]);
    console.log(e.target.files[0]);
  };
  const onSubmitImage = () => {
    document.getElementById("close").click();
    setLoading(true)
    const formData = new FormData();
    // if (image) {
    formData.append("image", image);
    axios
      .put(
        `${process.env.API_BACKEND}authWorker/update-profile/img`,
        formData,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
          "Content-Type": "multipart/form-data",
        }
      )
      .then((res) => {
        console.log(res);
        Swal.fire({
          icon: "success",
          title: res.data.message,
          confirmButtonText: "Oke",
        })
        fetch();
      });
    // }
  };
  useEffect(() => {
    fetch();
    fetchPort();
    fetchExp();
  }, []);
  return (
    <div className="body">
      <div className={`${styles.bg_profile}`}>
        <Head>
          <title>Hirejob</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/vercel.svg" />
        </Head>
        <Navbar />
        <div className={`${styles.bg}`}></div>
        <div className={`container ${styles.hight}`}>
          <div className="row mt-3 justify-content-center">
            <div className="col-lg-4 col-sm-8">
              <div className={`card mb-5 ${styles.border_none}`}>
                <div className={`card-body `}>
                  <div className={`${styles.img_profile}`}>
                    <div
                      className="edit-icon"
                      type="button"
                      data-bs-toggle="modal"
                      data-bs-target="#editPhoto"
                    >
                     {loading ? (
                        <div className="p-3 ms-5">
                          <div className="spinner-grow" role="status">
                            <span className="visually-hidden">Loading...</span>
                          </div>
                        </div>
                      ) : (
                        <Image
                          src={
                            detail.image
                              ? `https://drive.google.com/thumbnail?id=${detail.image}&sz=s1080`
                              : PhotoProfile
                          }
                          className={`${styles.img_profile}`}
                          priority={true}
                          layout="responsive"
                          width="100"
                          height="100"
                          alt="Photo Profile"
                        />
                      )}
                    </div>
                  </div>
                  <div
                    className="modal fade"
                    id="editPhoto"
                    tabIndex="-1"
                    aria-labelledby="editPhotoLabel"
                    aria-hidden="true"
                  >
                    <div className="modal-dialog">
                      <div className="modal-content">
                        <div className="modal-header">
                          <h5 className="modal-title" id="editPhotoLabel">
                            Change Photo Profile
                          </h5>
                          <button
                            type="button"
                            className="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"
                          />
                        </div>
                        <div className="modal-body">
                          <form>
                            <input
                              type="file"
                              className="form-control"
                              onChange={imageChangeHandler}
                            />
                          </form>
                        </div>
                        <div className="modal-footer">
                          <button
                            type="button"
                            id="close"
                            className="btn btn-secondary"
                            data-bs-dismiss="modal"
                          >
                            Close
                          </button>
                          <button
                            type="button"
                            onClick={onSubmitImage}
                            className="btn bg-primary text-white"
                          >
                            Save changes
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <h3>{detail?.fullname}</h3>
                  <h5>{detail?.jobs}</h5>
                  <p>{detail?.address}</p>
                  {/* <p>{detail?.job}</p> */}
                  <p>{detail.description ? detail.description : ``}</p>
                  <Link href="/edit-profile">
                    <button className={`btn ${styles.btn_custom}`}>
                      Edit Profile
                    </button>
                  </Link>

                  <p className="fw-1 fw-bold mt-5">Skill</p>
                  <div className="container text-center">
                    <div className="row gy-2">
                      {/* <div className={`border bg-warning ${styles.container_skill}`}> */}
                      {detail?.skill?.split(",").map((item, index) => (
                        <div className="col-4" key={index}>
                          <div>
                            <button className="btn bg-warning me-1 mt-2">
                              {item}
                            </button>
                          </div>
                        </div>
                      ))}
                      {/* </div> */}
                    </div>
                  </div>

                  <ul className="d-flex flex-column mt-5">
                    <li>
                      <i className="bi bi-envelope " /> Louistommo@gmail.com
                    </li>
                    <li>
                      <i className="bi bi-instagram " /> @Louist91
                    </li>
                    <li>
                      <i className="bi bi-github " /> @Louistommo
                    </li>
                    <li>
                      <i className="bi bi-linkedin " /> @Louistommo91
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div className="col-lg-8 col-sm-8">
              <div className={`card mb-5 ${styles.border_none}`}>
                <div className="card-body">
                  <div className="utama">
                    <nav>
                      <div className="nav nav-tabs" id="nav-tab" role="tablist">
                        <button
                          className={`nav-link active ${styles.under_line}`}
                          id="nav-home-tab"
                          data-bs-toggle="tab"
                          data-bs-target="#nav-home"
                          type="button"
                          role="tab"
                          aria-controls="nav-home"
                          aria-selected="true"
                        >
                          Portofolio
                        </button>
                        <button
                          className="nav-link"
                          id="nav-profile-tab"
                          data-bs-toggle="tab"
                          data-bs-target="#nav-profile"
                          type="button"
                          role="tab"
                          aria-controls="nav-profile"
                          aria-selected="false"
                        >
                          Pengalaman Kerja
                        </button>
                      </div>
                    </nav>
                    <div className="tab-content mt-5" id="nav-tabContent">
                      <div
                        className="tab-pane fade show active"
                        id="nav-home"
                        role="tabpanel"
                        aria-labelledby="nav-home-tab"
                        tabIndex="0"
                      >
                        <Portofolio data={portfolio} />
                      </div>
                      <div
                        className="tab-pane fade"
                        id="nav-profile"
                        role="tabpanel"
                        aria-labelledby="nav-profile-tab"
                        tabIndex="0"
                      >
                        <Pengalaman data={experience} />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Profile;
