import Head from "next/head";
import React, { useEffect,  useState } from "react";
import styles from "../../styles/Profile.module.css";
import Image from "next/image";
import PhotoProfile from "../../assets/iconOffice.svg";
import axios from "axios";
import Link from "next/link";
import Footer from "../../components/footer/Footer";
import Navbar from "../../components/Navbar/NavbarDetail";
import Cookies from "js-cookie";
import Swal from "sweetalert2";

const Profile = () => {
  const id = Cookies.get("id");
  const token = Cookies.get("token");
  const [image, setImage] = useState(null);
  const [detail, setDetail] = useState([]);
  const [loading, setLoading] = useState(false);
  const [portfolio, setPortfolio] = useState([]);
  const [experience, setExperience] = useState([]);
  console.log(portfolio);
  console.log(experience);
  console.log(detail);
  const fetch = async () => {
    try {
      const result = await axios.get(
        `${process.env.API_BACKEND}authRecruiter/profile`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );
      setDetail(result.data.data[0]);
      setLoading(false);
      
    } catch (err) {
      console.log(err)
    }
    }
  const fetchPort = async () => {
    const result = await axios.get(`${process.env.API_BACKEND}portfolio/${id}`);

    setPortfolio(result.data.data);
  };

  const fetchExp = async () => {
    const result = await axios.get(
      `${process.env.API_BACKEND}experience/${id}`
    );

    setExperience(result.data.data[0]);
  };

  const imageChangeHandler = (e) => {
    setImage(e.target.files[0]);
    console.log(e.target.files[0]);
  };
  const onSubmitImage = async() => {
    document.getElementById("close").click();
    setLoading(true)
    const formData = new FormData();
    // if (image) {
    formData.append("image", image);
    await axios
      .put(
        `${process.env.API_BACKEND}authRecruiter/update-profile/img`,
        formData,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
          "Content-Type": "multipart/form-data",
        }
      )
      .then((res) => {
        console.log(res.data.data.payload);
        if(res.data.data.payload){
          Swal.fire({
            icon: "error",
            title: "insert Photo",
            confirmButtonText: "Oke",
          })
        }else{
          Swal.fire({
            icon: "success",
            title: res.data.message,
            confirmButtonText: "Oke",
          })
        }
      
        fetch();
      });
    // }
  };
  useEffect(() => {
    fetch();
    fetchPort();
    fetchExp();
  }, []);
  return (
    <div className="body">
      <div className={`${styles.bg_profile}`}>
        <Head>
          <title>Hirejob</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/vercel.svg" />
        </Head>
        <Navbar />
        <div className={`container mt-5`}>
          <div className="row mt-3 justify-content-center">
            <div className="col-lg col-sm-8">
            <div className={`${styles.bg1}`}></div>
              <div className={`card mb-5 ${styles.border_none}`}>
                <div className={`card-body ${styles.border_none1}`}>
                  <div className={`${styles.img_profile}`}>
                    <div
                      className="edit-icon"
                      type="button"
                      data-bs-toggle="modal"
                      data-bs-target="#editPhoto"
                    >
                     {loading ? (
                        <div className="p-3 ms-5">
                          <div className="spinner-grow" role="status">
                            <span className="visually-hidden">Loading...</span>
                          </div>
                        </div>
                      ) : (
                        <Image
                          src={
                            detail.image
                              ? `https://drive.google.com/thumbnail?id=${detail.image}&sz=s1080`
                              : PhotoProfile
                          }
                          className={`${styles.img_profile}`}
                          priority={true}
                          layout="responsive"
                          width="50"
                          height="50"
                          alt="Photo Profile"
                        />
                      )}
                    </div>
                  </div>
                  <div
                    className="modal fade"
                    id="editPhoto"
                    tabIndex="-1"
                    aria-labelledby="editPhotoLabel"
                    aria-hidden="true"
                  >
                    <div className="modal-dialog">
                      <div className="modal-content">
                        <div className="modal-header">
                          <h5 className="modal-title" id="editPhotoLabel">
                            Change Photo Profile
                          </h5>
                          <button
                            type="button"
                            className="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"
                          />
                        </div>
                        <div className="modal-body">
                          <form>
                            <input
                              type="file"
                              className="form-control"
                              onChange={imageChangeHandler}
                            />
                          </form>
                        </div>
                        <div className="modal-footer">
                          <button
                            type="button"
                            id="close"
                            className="btn btn-secondary"
                            data-bs-dismiss="modal"
                          >
                            Close
                          </button>
                          <button
                            type="button"
                            onClick={onSubmitImage}
                            className="btn bg-primary text-white"
                          >
                            Save changes
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="text-center">
                    <h3>{detail?.company}</h3>
                    <h5>{detail?.company_field}</h5>
                    <p>{detail?.address}</p>
                    {/* <p>{detail?.job}</p> */}
                    <p>{detail.company_description ? detail.company_description : ``}</p>
                  </div>
                  <div className="container w-50">
                    <Link href="/edit-recruiter">
                      <button className={`btn ${styles.btn_custom}`}>
                        Edit Profile
                      </button>
                    </Link>
                    <div className=" d-flex w-100 mt-5 text-secondary text-decoration-none flex-column align-items-center fs-5">
                      <div className="d-flex flex-column">
                        <span className="mb-3">
                          <i className="bi bi-envelope me-3" /> {detail.email}
                        </span>
                        <span className="mb-3">
                          <i className="bi bi-instagram me-3" /> {detail.instagram}
                        </span>
                        <span className="mb-3">
                          <i className="bi bi-github me-3" /> {detail.phonenumber}
                        </span>
                        <span className="mb-3">
                          <i className="bi bi-linkedin me-3" /> {detail.linkedin}
                        </span>
                      </div>

                    </div>

                  </div>
                </div>
              </div>
            </div>
            {/* <div className="col-lg-8 col-sm-8">
              <div className={`card mb-5 ${styles.border_none}`}>
                <div className="card-body">
                  <div className="utama">
                    <nav>
                      <div className="nav nav-tabs" id="nav-tab" role="tablist">
                        <button
                          className={`nav-link active ${styles.under_line}`}
                          id="nav-home-tab"
                          data-bs-toggle="tab"
                          data-bs-target="#nav-home"
                          type="button"
                          role="tab"
                          aria-controls="nav-home"
                          aria-selected="true"
                        >
                          Portofolio
                        </button>
                        <button
                          className="nav-link"
                          id="nav-profile-tab"
                          data-bs-toggle="tab"
                          data-bs-target="#nav-profile"
                          type="button"
                          role="tab"
                          aria-controls="nav-profile"
                          aria-selected="false"
                        >
                          Pengalaman Kerja
                        </button>
                      </div>
                    </nav>
                    <div className="tab-content mt-5" id="nav-tabContent">
                      <div
                        className="tab-pane fade show active"
                        id="nav-home"
                        role="tabpanel"
                        aria-labelledby="nav-home-tab"
                        tabIndex="0"
                      >
                        <Portofolio data={portfolio} />
                      </div>
                      <div
                        className="tab-pane fade"
                        id="nav-profile"
                        role="tabpanel"
                        aria-labelledby="nav-profile-tab"
                        tabIndex="0"
                      >
                        <Pengalaman data={experience} />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div> */}
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Profile;
