import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/Navbar";
import { Fragment } from "react";
import Baner from "../components/header/Baner";
import Footer from "../components/footer/Footer";
import Peler from "./api/index";

// export async function getStaticProps() {
//   const detail = await Peler()
//   console.log("ini detail", detail)
//   console.log(detail);
//   return { props: { detail } };
// }
export default function Home({ detail }) {
  // console.log(detail)
  return (
    <Fragment>
      <div className="body">
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/vercel.svg" />
          </Head>
          <Navbar />
          <Baner />
        </div>
        <Footer />
      </div>
    </Fragment>
  );
}
